<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>

<?php
$this->title = \WS::t('profile', 'My Profile');
$this->params['breadcrumbs'][] = $this->title;
?>

<h2 class="title"><?php echo $this->title?></h2>

<?php $form = ActiveForm::begin(['id' => 'customer-profile-form'])?>

    <div class="form-group">
        <?php echo $form->field($profile, 'name') ?>
    </div>

    <div class="form-group">
        <?php echo $form->field($profile, 'phone_number') ?>
    </div>

    <div class="form-group">
        <?php echo $form->field($profile, 'job_name') ?>
    </div>

    <div class="form-group">
        <?php echo $form->field($profile, 'where_from')->dropDownList(\common\customer\Profile::whereFromOptions(), ['prompt'=>'']) ?>
    </div>

    <div class="container-fluid">
        <div class="row">
            <button type="submit" class="btn"><?php echo \WS::t('profile', 'Submit')?></button>
        </div>
    </div>
<?php ActiveForm::end()?>