<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$t = \WS::lang('account');
$this->title = tt("My account", '我的帐户');
?>

<?php
$this->params['breadcrumbs'][] = $this->title;
?>

<h2 class="title"><?php $t('Modify your Password.')?></h2>

<?php if($modifyPasswordForm->result):?>
    <div class="alert alert-success"><?php $t('Password modification has been completed!')?></div>
<?php endif?>

<div>
    <?php $form = ActiveForm::begin(['id' => 'modify-password-form'])?>

        <div class="form-group">
            <?php echo $form->field($modifyPasswordForm, 'old_password')->passwordInput() ?>
        </div>

        <div class="form-group">
            <?php echo $form->field($modifyPasswordForm, 'password')->passwordInput() ?>
        </div>

        <div class="form-group">
            <?php echo $form->field($modifyPasswordForm, 'confirm_password')->passwordInput() ?>
        </div>
        
        <div class="container-fluid">
            <div class="row">
                <button type="submit" class="btn"><?php $t('Submit')?></button>
            </div>
        </div>
    <?php ActiveForm::end()?>
</div>
<style>
#modify-password-form .form-control{width:250px;}
</style>