<?php 
    use yii\widgets\Block;
    use yii\bootstrap\Nav;
    use yii\bootstrap\NavBar;
    use yii\widgets\Breadcrumbs;
    use \module\page\widgets as PageWidget;
?>

<?php $this->beginContent('@module/page/views/layouts/base.phtml')?>

<div id="main">
    <?php echo \module\page\widgets\Nav::widget()?>
    <?php if (isset($this->params['breadcrumbs']) && count($this->params['breadcrumbs']) > 0):?>
        <div class="page-breadcrumb-container">
            <div class="container">
                <?php 
                    echo yii\widgets\Breadcrumbs::widget([
                        'encodeLabels'=>false,
                        'itemTemplate' => "<li><i>{link}</i></li>\n", // template for all links
                        'links' => $this->params['breadcrumbs']
                    ]);
                ?>
            </div>
        </div>
    <?php endif?>
    
    <div class="container">
        <?php foreach (Yii::$app->session->getAllFlashes() as $key => $message) { ?>
            <div class="alert alert-<?=$key?>" role="alert"><?=$message?></div>
        <?php } ?>
    </div>

    <?php echo $content;?>
</div>

<?php echo PageWidget\FooterBefore::widget()?>

<?php echo PageWidget\Footer::widget()?>

<?php $this->endContent()?>