<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use common\customer\RetsNewsletter;

$t = \WS::lang('rets-nl');
?>

<?php
$this->title = tt('Newsletter Notification', '订阅通知');
$this->params['breadcrumbs'][] = $this->title;
?>

<?php if($model->id):?>
    <h2 class="title"><?php _tt('Modify Newsletter Notification', '修改订阅通知')?></h2>
<?php else:?>
    <h2 class="title"><?php _tt('Create a Newsletter Notification', '创建订阅通知')?></h2>
<?php endif?>
<div class="">
<?php $form = ActiveForm::begin([
         'id' => 'rets-newsletter-form', 
         'layout'=>'horizontal',
         'fieldConfig' => [
            'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
            'horizontalCssClasses' => [
                'label' => 'col-sm-2',
                'offset' => 'col-sm-offset-2',
                'wrapper' => 'col-sm-6',
                'error' => '',
                'hint' => '',
            ],
      ],
      ])?>

    <?php if (!$model->area_id):?>
        <h2 style="font-size:18px;margin-bottom:10px;"><?php echo tt('Plase choose area first blow', '请先选择区域')?></h2>
        <ul style="margin-left:15px;">
            <?php foreach ($areas as $id => $name):?>
                <li style="padding:3px 0"><a href="/rets/newsletter/edit/?area_id=<?php echo $id?>"><?php echo $name?></a></lii>
            <?php endforeach?>
        </ul>
    <?php else:?>
        <div style="padding: 0 0 15px 15px;font-size: 24px;margin-bottom: 10px;">
            <?php echo $areas[$model->area_id]?>
        </div>

        <?php echo $form->field($model, 'name', ['horizontalCssClasses'=>['wrapper'=>'col-sm-6']])?>

        <?php echo $form->field($model, 'city', ['horizontalCssClasses'=>['wrapper'=>'col-sm-3']])
            ->dropDownList(RetsNewsletter::cityOptions($areaId), ['prompt'=>'', 'class'=>'form-control ex-select']) ?>

        <?php echo $form->field($model, 'prop_type', ['horizontalCssClasses'=>['wrapper'=>'col-sm-3']])
            ->dropDownList(RetsNewsletter::typeOptions(), ['prompt'=>'']) ?>

        <?php echo $form->field($model, 'price_range', ['horizontalCssClasses'=>['wrapper' => 'col-sm-8']]) ?>

        <?php echo $form->field($model, 'bed_rooms')
            ->inline()
            ->radioList(RetsNewsletter::bedOptions()) ?>

        <?php echo $form->field($model, 'bath_rooms')
            ->inline()
            ->radioList(RetsNewsletter::bathOptions()) ?>

        <?php echo $form->field($model, 'notification_cycle')
            ->inline()
            ->radioList(RetsNewsletter::cycleOptions()) ?>

        <div class="container-fluid">
            <div class="row">
                <button type="submit" class="btn"><?php _tt('Submit', '提交')?></button>
                &nbsp;&nbsp;
                <a href="/umember/rets-newsletter/" class="btn"><?php _tt('Cancel', '取消')?></a>
            </div>
        </div>
        <?php endif?>
<?php ActiveForm::end()?>
</div>

<style>
.form-horizontal .control-label{text-align:left;}
.form-horizontal .form-group{margin-left:0;margin-right:0;}
.price-range-input{display:inline-block;width:85px;}
</style>
<script>
(function($){
    var $priceRange = $('#retsnewsletter-price_range');
    var prices = $priceRange.val().split('-');
    if(prices.length < 2) prices.push('');
    var $inputs = '$ <input id="price-range-begin" class="form-control price-range-input" value="'+prices[0]+'"/>' +
                  ' - '+
                  '$ <input id="price-range-end" class="form-control price-range-input" value="'+prices[1]+'"/>'

    $priceRange.after($inputs);
    $priceRange.hide();
    $('.field-retsnewsletter-price_range').delegate('.price-range-input', 'change', function(event) {
        var result = $('#price-range-begin').val()+'-'+$('#price-range-end').val();
        $priceRange.val(result);
    });
})(jQuery);

</script>