<?php
use yii\helpers\Html;
use yii\grid\GridView;
use common\customer\RetsNewsletter;

$this->title = tt('Newsletter Notification', '订阅通知');  
$this->params['breadcrumbs'][] = $this->title;  
?>

<h2 class="title"><?php echo $this->title?>
    <a href="edit/" class="btn" style="float:right"><?php echo tt('New', '创建')?></a>
</h2>

<?php
$typeOptions = RetsNewsletter::typeOptions();
echo yii\grid\GridView::widget([
    'id'=>'uc-newsletter-grid',
    'layout'=>"{pager}\n{items}\n{pager}",
    'tableOptions'=>['class'=>'table'],
    'dataProvider' => $dataProvider,
    'columns'=>[
        'prop_type'=>[
            'attribute'=>'prop_type',
            'value'=>function($m) use($typeOptions){
                return isset($typeOptions[$m->prop_type]) ? $typeOptions[$m->prop_type] : null;
            },
            'headerOptions'=>[
                'width'=>'80px'
            ]
        ],
        'name'=>[
            'attribute'=>'name',
            'headerOptions'=>[
                'width'=>'120px'
            ]
        ],
        'info'=>[
            'header'=>tt('Info', '内容'),
            'value'=>function($m) {
                $dataItems = $m->getDataItems();
                $output = [];
                foreach ($dataItems as $label => $value) {
                    $output[] = "<span class=\"label label-default\"><i>{$label}</i>:{$value}</span>";
                }
                return implode('&nbsp;', $output);
            },
            'format'=>'html'
        ],
        'created_at'=>[
            'attribute'=>'created_at',
            'format'=>'date',
            'headerOptions'=>[
                'width'=>'120px'
            ]
        ],
        [
           'class' => '\yii\grid\ActionColumn',
           'header' => tt('Action', '操作'), 
           'template' => '{update}{delete}',
           'headerOptions' => ['width' => '50'],
           'contentOptions'=>[
                'align'=>'center'
           ]
        ],
    ]
]);