<?php
use yii\helpers\Html;
use yii\grid\GridView;
use common\customer\RetsNewsletter;

$this->title = tt('Newsletter Notification', '订阅通知');  
$this->params['breadcrumbs'][] = $this->title;  
?>

<h2 class="title"><?php echo $this->title?>
    <a href="edit/" class="btn" style="float:right"><?php echo tt('New', '创建')?></a>
</h2>

<style type="text/css">
.filters .cell-label{
    color:#666;
    padding-left:5px;
    padding-right:10px;
    text-align:right;
    background-color:#f2f2f2;
    border-bottom:solid 3px #fff;
}
.filters .cell-label:after{
    content:':';
}
.filters .cell-value{
    padding-left:8px;
}
</style>

<?php
$typeOptions = RetsNewsletter::typeOptions();
echo yii\grid\GridView::widget([
    'id'=>'uc-newsletter-grid',
    'layout'=>"{pager}\n{items}\n{pager}",
    'tableOptions'=>['class'=>'table'],
    'dataProvider' => $dataProvider,
    'columns'=>[
        'name'=>[
            'attribute'=>'name',
            'headerOptions'=>[
                'width'=>'170px'
            ]
        ],
        'info'=>[
            'header'=>tt('Info', '内容'),
            'value'=>function($m) {
                $dataItems = $m->getDataItems();
                $output = ['<table class="filters">'];
                foreach ($dataItems as $label => $value) {
                    if ($value && strlen($value) > 0) {
                        $output[] = '<tr>';
                        $output[] = "<td class=\"cell-label\">{$label}</td>";
                        $output[] = "<td class=\"cell-value\">{$value}</td>";
                        $output[] = '</tr>';
                    }
                }
                $output[] = '</table>';
                return implode('', $output);
            },
            'format'=>'html'
        ],
        'created_at'=>[
            'attribute'=>'created_at',
            'headerOptions'=>[
                'width'=>'140px'
            ],
            'value'=>function($m) {
                return date('Y-m-d H:00', strtotime($m->created_at));
            }
        ],
        [
           'class' => '\yii\grid\ActionColumn',
           'header' => tt('Action', '操作'), 
           'template' => '{update}&nbsp;{delete}',
           'headerOptions' => ['width' => '50'],
           'contentOptions'=>[
                'align'=>'center'
           ]
        ],
    ]
]);
?>